Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/AbcSize: 
  Enabled: false